### ISSUE TITLE
프로젝트 피드백

### ISSUE THREAD

**Issue by DevelopSoo** [sobbingtofu/prjHarryPotterArchive#10]
1. title, description 적절하게 바꾸세용
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/044c25bfca2f5bdd5ecd04093d1a4a3f4943aa1f/src/app/layout.tsx#L9-L12

2. 파일 이름 오타 났습니다.
commets.type.ts -> comments.type.ts
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/types/commets.type.ts#L1-L12

3. api route 혹은 서버쪽에서는 사용하지 못할 것 같은데 괜찮나요?https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/lib/supabase.ts#L1-L8

4. console.log 지웁시다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/ArrangeToggle/ArrangeToggle.tsx#L11

5. 굳이 3번 선언 하지 않고 이렇게 하면 더 간단하지 않나요?
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/ArrangeToggle/ArrangeToggle.tsx#L7-L9

```
  const {
    arrangeOption: currentArrangeOption,
    setArrangeToLatest,
    setArrangeToLikes,
  } = zustandStore((state) => state)
```

6. 클라이언트 컴포넌트에서 API 요청 시 api route handler를 활용하는 것이 이번 과제 요구사항입니다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/auth/Signup.tsx#L69-L72
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/auth/Signup.tsx#L83-L85

7. 안쓰는 import 문은 삭제합니다
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/character/paginatedPage.tsx#L14
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/character/paginatedPage.tsx#L16

8. src/components/character/paginatedPage.tsx 라는 구조가 다소 어색합니다. character랑 무슨 상관인가요?

9. if 문으로만 바꿀 수도 있을 것 같습니다. return 문 덕에 else if 안써도 됩니다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/CharacterList/CharacterList.tsx#L39-L44
```
  if (isPending) {
    return <Loader />
  }
  if (isError) {
    return <div>데이터 불러오던 중 오류가 발생했습니다.</div>
  }
 // 그외 코드 
```

10. onAuthStateChange 하나로만 하면 되지 않나요? getSession 함수를 만들어야 하나요?
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/Header/Header.tsx#L15-L34

11. 클라이언트 컴포넌트에서 supabase 코드 요청 시 api route handler를 연습해봅시다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/Header/Header.tsx#L15-L26

12. error 발생 시 콘솔로만 찍으면 사용자는 모릅니다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/Header/Header.tsx#L45

13. 타입에러 발생합니다. 타입에러나면 배포 안됩니다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/house-tests/page.tsx#L107-L126

14. Image 컴포넌트로 변경해봅시다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/house-tests/page.tsx#L133
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/house-tests/page.tsx#L178

15. 삼항연산자가 중첩되어 코드를 이해하기가 어렵습니다. 중첩하지 않을 방법을 고민해봅시다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/house-tests/page.tsx#L130-L183

16. 삼항 연산자가 중첩되어 이해하기 어렵습니다. 
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/MovieCard/MovieCard.tsx#L12-L16

17. state와 관련없는 함수가 컴포넌트 안에 있으면 계속 재생성되기 때문에 컴포넌트 밖으로 빼는 것이 좋습니다. 

18. 함수가 굉장히 길고 많네요. 커스텀 훅으로 분리하여 UI로직과 비즈니스 로직을 분리하는 것도 좋은 방법입니다.
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/movieDetail/Comments.tsx#L44-L194

19. 이거 어차피 아래에서 map 돌리는데 왜하나요?
https://github.com/sobbingtofu/prjHarryPotterArchive/blob/66d511678da75fae0fbb39a81bb2a05274d364e5/src/components/movieDetail/OtherSeries.tsx#L17-L24

**Comment by DevelopSoo** [comment]
너무 많아서 다는 못했습니다. 추후 또 추가하겠습니다.

**Comment by sobbingtofu** [comment]
감사합니다 튜터님!

**Comment by hyejinleeee** [comment]
감사합니다 튜터님 !!

**Comment by sobbingtofu** [comment]
삼항연산자의 중첩에 따른 가독성 저하 문제는 여러모로 해결을 시도했으나, next-js의 Image 태그에 fill 속성을 쓸 때 부모요소가 relative여야 한다는 조건에 걸려서 오류가 발생하는 경우가 잦아 일단 해결을 보류했습니다. 그것 외에는 제가 맡았던 부분에선 튜터님의 피드백 잘 반영해봤습니다. 감사합니다 튜터님 :)
